
# databag template for pgbouncer-extra-config requirer:
# this data will be put in the application/unit databag of any relation bound on require-pgbouncer-extra-config

# must be str:str
app_data: 
    # foo: bar
    
# must be str:str
units_data:
    # baz: qux
