
# databag template for grafana_cloud_config requirer:
# this data will be put in the application/unit databag of any relation bound on require-grafana_cloud_config

# must be str:str
app_data: 
    # foo: bar
    
# must be str:str
units_data:
    # baz: qux
