# endpoint name = ``["provide"|"require"]-[interface name]``
endpoint: "provide-your_interface"
# json-encoded app databag contents
app_data: '{"hello":"world"}'
# json-encoded unit databag contents
unit_data: '{"hello":"world"}'
