
# databag template for apache-vhost-config provider:
# this data will be put in the application/unit databag of any relation bound on provide-apache-vhost-config

# must be str:str
app_data: 
    # foo: bar
    
# must be str:str
units_data:
    # baz: qux
